version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  judge-worker:
    image: judge-worker:latest
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'       # 限制最多使用1个CPU核心
          memory: 1024M     # 限制最多使用1GB内存
        reservations:
          cpus: '0.5'       # 保留0.5个CPU核心
          memory: 512M      # 保留512MB内存
