spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 消息队列并发参数配置
    concurrent-consumers: 8
    max-concurrent-consumers: 15
    prefetch-count: 3
    # 连接池配置
    cache:
      channel:
        size: 25
        checkout-timeout: 0
    # 发布确认
    publisher-confirm-type: correlated
    # 发布返回
    publisher-returns: true
    # 模板配置
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0

# Docker 执行器配置
executor:
  memory-limit-mb: 256
  cpu-limit: 1
  pool-size: 7   # 减少初始容器池大小，因为使用异步执行
  max-containers: 20  # 减少最大容器数，避免资源浪费
  # 容器清理策略配置
  enable-pre-cleanup: false   # 是否启用获取容器前的预清理
  enable-post-cleanup: true  # 是否启用释放容器后的后清理

# Docker配置
docker:
  host: tcp://localhost:2375  # Windows Docker Desktop TCP连接
  connection-timeout: 30000
  read-timeout: 60000
  max-connections: 100
  max-connections-per-route: 10

# 实例配置
instance:
  id: ${INSTANCE_ID:}  # 可选：手动指定实例ID，如果不指定则自动生成

logging:
  level:
    cn.icongyou: info
    com.github.dockerjava: warn  # 减少docker-java的日志输出
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8081
  # 增加服务器线程池
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 100

