spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 连接池配置
    cache:
      connection:
        mode: channel
      channel:
        size: 25
        checkout-timeout: 0
    # 发布确认
    publisher-confirm-type: correlated
    # 发布返回
    publisher-returns: true
    # 模板配置
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
  
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
    # Redis集群配置（可选）
    # cluster:
    #   nodes:
    #     - localhost:7001
    #     - localhost:7002
    #     - localhost:7003

server:
  port: 8080
  # 增加服务器线程池
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 100

# 应用配置
app:
  # 结果缓存时间（秒）
  result-cache-ttl: 3600
  # 最大并发请求数
  max-concurrent-requests: 1000
  # 请求队列大小
  request-queue-size: 5000
